#!/usr/bin/env python3
"""The conservation challenge: two ledgers, one leaked unit.

Exact-integer conservation accounting is one of our core disciplines: books
that close to ZERO, not to "approximately zero". Here are two energy ledgers,
each 4,096 integer transfer entries among 64 accounts, generated by the same
deterministic program. In one of them, a single entry was altered by ONE unit
-- one part in billions of total flow. No statistic will find it fast; the
books find it instantly, because conservation is not a vibe, it is a sum.

    python tools/conservation_challenge.py            # regenerate both ledgers
    python tools/conservation_challenge.py --audit assets/ledger-a.json
    python tools/conservation_challenge.py --audit assets/ledger-b.json

An honest ledger prints BOOKS CLOSE (every account's inflow minus outflow
matches its declared balance, and the global sum is exactly zero). The forged
one names the exact account where conservation breaks.
"""

import hashlib
import json
import os
import sys

N_ACCOUNTS = 64
N_ENTRIES = 4096
SEED = 0xC0135E17
FORGE_ENTRY = 2717            # this entry's amount is altered by exactly 1

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSETS = os.path.join(ROOT, "assets")


def lcg(seed):
    s = seed
    while True:
        s = (s * 6364136223846793005 + 1442695040888963407) & ((1 << 64) - 1)
        yield s >> 33


def build(forged):
    rnd = lcg(SEED)
    entries = []
    for i in range(N_ENTRIES):
        src = next(rnd) % N_ACCOUNTS
        dst = (src + 1 + next(rnd) % (N_ACCOUNTS - 1)) % N_ACCOUNTS
        amount = 1 + next(rnd) % 999_983
        if forged and i == FORGE_ENTRY:
            amount += 1          # the leak: one unit, one entry
        entries.append({"i": i, "from": src, "to": dst, "amount": amount})
    balances = [0] * N_ACCOUNTS
    # declared balances are computed from the HONEST flows in both ledgers --
    # so the forged ledger's declarations no longer match its own entries.
    rnd2 = lcg(SEED)
    for i in range(N_ENTRIES):
        src = next(rnd2) % N_ACCOUNTS
        dst = (src + 1 + next(rnd2) % (N_ACCOUNTS - 1)) % N_ACCOUNTS
        amount = 1 + next(rnd2) % 999_983
        balances[src] -= amount
        balances[dst] += amount
    ledger = {"spec": "cel/conservation-challenge/v1", "accounts": N_ACCOUNTS,
              "declared_balances": balances, "entries": entries}
    blob = (json.dumps(ledger, separators=(",", ":"), sort_keys=True) + "\n").encode()
    return blob


def audit(path):
    data = json.loads(open(path, "rb").read())
    balances = [0] * data["accounts"]
    total = 0
    for e in data["entries"]:
        balances[e["from"]] -= e["amount"]
        balances[e["to"]] += e["amount"]
        total += 0  # transfers conserve globally by construction; the check is per-account
    bad = [i for i in range(data["accounts"])
           if balances[i] != data["declared_balances"][i]]
    if not bad:
        print(f"BOOKS CLOSE: {len(data['entries'])} entries, "
              f"{data['accounts']} accounts, every balance exact, drift = 0.")
        sys.exit(0)
    for i in bad:
        drift = balances[i] - data["declared_balances"][i]
        print(f"CONSERVATION BROKEN at account {i}: computed {balances[i]}, "
              f"declared {data['declared_balances'][i]} (drift {drift:+d} unit).")
    print("This ledger is forged.")
    sys.exit(1)


def main():
    if "--audit" in sys.argv:
        audit(sys.argv[sys.argv.index("--audit") + 1])
    os.makedirs(ASSETS, exist_ok=True)
    for label, forged in (("a", False), ("b", True)):
        blob = build(forged)
        p = os.path.join(ASSETS, f"ledger-{label}.json")
        with open(p, "wb") as f:
            f.write(blob)
        print(f"wrote assets/ledger-{label}.json  sha256={hashlib.sha256(blob).hexdigest()[:16]}...")


if __name__ == "__main__":
    main()
